### PR TITLE
add FastNoise Lite beef port

### PR DESCRIPTION
**Pull request by EinScott**
Noise is useful. FastNoise is easy to use and includes multiple noise functions. I put it in a new "noise" category, since it didnt seem to fit nicely anywhere else.

### CODE REVIEW

**Comment by Jonathan-Racaud** [comment]
Would a **Math** category works? Or perhaps simply **Algorithms** ?

And then we could have a sub-category specifically for _noise_.

**Comment by EinScott** [comment]
that sounds good. Then the hash stuff would also go there. I was very tempted to put it there, it kind of relates, but not really.

**Comment by EinScott** [comment]
So how about this? I'm not totally sure about the ### headlines though. Or maybe they should just not be mentioned in the lookup table?

**Comment by Jonathan-Racaud** [comment]
I think it's okay like that. We don't have a lot of categories at the moment.

**Pull request merged**
